aliases:
  - &restore-cache
    keys:
      - dependencies-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "requirements.txt" }}-{{ checksum "yarn.lock.txt" }}

  - &save-cache
    paths:
      - venv
      - node_modules
    key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "requirements.txt" }}-{{ checksum "yarn.lock.txt" }}

version: 2
jobs:
  build:
    docker:
      # - image: circleci/python:2.7-node-browsers-legacy
      - image: circleci/python:2-node
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run: yarn install --frozen-lockfile
      - run: git submodule update --init --recursive
      - run:
          command: |
            . venv/bin/activate
            make publish
      - save_cache: *save-cache
  deploy:
    docker:
      - image: circleci/python:2.7-node
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run:
          name: Copy files to S3
          command: python ./deploy_to_s3.py

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
        #   filters:
        #     branches:
        #       only: master
