version: 2
jobs:
  install:
    docker:
      # - image: circleci/python:2.7-node-browsers-legacy
      - image: circleci/python:2-node
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: pip install -r requirements.txt
      - run: git submodule update --init --recursive
      - run: make publish
  deploy:
    docker:
      - image: circleci/python:2.7-node
    steps:
      - checkout
      - run: echo 'hello'
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - deploy
